### ISSUE TITLE
Desligar o RGB

### ISSUE THREAD

**Issue by fematarazzo** [andreldm/harpoond#2]
Oi Andre, tudo bem?

Vi que você é BR, então facilita aqui.

Eu fiz o git clone do projeto e dei uma olhada no harpoond.c, lá pela linha 116, e tentei alterar os valores.
De fato, eles mudaram de cor, mas não consegui desabilitar...

Você consegue me ajudar?

Abraços!

**Comment by andreldm** [comment]
Opa Felipe, tudo bem.
Então, configuração padrão já desliga o RGB principal e deixa o LED do botão próximo à rodinha verde.
Seria esse último LED que você deseja desabilitar? Se sim é só trocar `0xff`na linha 120 por `0x00`.

Aqui funciona bem, talvez o modelo do seu mouse seja outro, na etiqueta do meu tem "Model: RGP0075".

**Comment by fematarazzo** [comment]
Fala, Andre!
Verdade, acabei de ver que funciona quando fica o mouse ta wired!
Apesar de que, na configuração padrão, a luz desliga, mas os "perfis" de DPI somem, né? Pelo menos no meu caso fica só o verde.

E não funciona no bluetooth, né...somente wired ou 2.4Ghz, certo?

**Comment by andreldm** [comment]
Sim, Felipe, fica apenas um perfil e também não é compatível com bluetooth, como dito no README é fora do escopo.
Vou fechar esta issue visto que o projeto está funcionando como esperado, qualquer dúvida favor reabrir.
