### ISSUE TITLE
libusb.h error No such file or directory

### ISSUE THREAD

**Issue by renansouza-dev** [andreldm/harpoond#4]
Hello Andre, how are you?

I'm using Pop!_OS distro and I have to do some workaround because I had some trouble with **libusb.h** while executing make. It returns an error with the message **No such file or directory**.

I run `sudo apt-get install libusb-1.0-0-dev` and then updated the harpoond.c from `#include <libusb.h>` to `#include <libusb-1.0/libusb.h>`.

Now everything is working as expected.
I'm just posting this if some else faces the same problem, including me in the future.

**Comment by andreldm** [comment]
Hi Renan, thanks for the suggestion, I have added a note about dependencies in 7ddf5999.

With regards to `#include <libusb-1.0/libusb.h>`, this shouldn't be necessary, in the Makefile `pkg-config` is used to get CFLAGS with the include path to this lib. What does `pkg-config --cflags libusb-1.0` yield for you?

**Comment by renansouza-dev** [comment]
Andre,

The result is `-I/usr/include/libusb-1.0`

**Comment by andreldm** [comment]
Weird, works for me:
```
docker run -it --rm -v $PWD:/harpoond ubuntu:20.04
apt update && apt install make gcc libusb-1.0-0-dev pkgconf
cd /harpoond && make
```

**Comment by renansouza-dev** [comment]
I suppose it's cuz I'm using System Pop! Off-topic: have you trouble connecting harpoon over bt? I have tried some Linux distro and had the same outcome... It's listed but does not connect!

**Comment by andreldm** [comment]
> I suppose it's cuz I'm using System Pop!

Maybe, though it shouldn't be a problem as pop is based on ubuntu.

> Off-topic: have you trouble connecting harpoon over bt? I have tried some Linux distro and had the same outcome... It's listed but does not connect!

No, works fine here (Arch, bluez 5.58, blueman 2.1.4).

**Comment by renansouza-dev** [comment]
Same specs here, but still won't connect over bt. Thanks anyway.
