### ISSUE TITLE
How did you figure out hex of commands? I want find out how to change dpi diod color

### ISSUE THREAD

**Issue by DAigory** [andreldm/harpoond#7]
Do you have suggestion to how to find it?

**Comment by andreldm** [comment]
Hi @DAigory, those commands were found after a couple of reverse engineering sessions with iCUE and Wireshark.

See the links at [prototype.py](https://github.com/andreldm/harpoond/blob/master/prototype.py), they contain all the info you need to make iCUE spill the beans :smile:

Also notice that iCUE will send lots of commands during its initialization and from time to time the "keep alive" signal, you'll need a bit of patience to find the important commands among the noise.

I hope this helps, I'm closing the issue, reopen if you still need help.
